### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by AleksandrKashirin** [OpenTeleVision/TeleVision#1]
Hi!
The provided instructions are not sufficient for utilization. Could you please provide more clear documentation on running and utilization?

Thank you!

**Comment by AleksandrKashirin** [comment]
I am using Oculus Quest 3 and created a local certificate. I have started the example script with zed camera and then started ngrok server and nothing is appeared.

**Comment by chengxuxin** [comment]
Hi, if you use local certificate, then ngrok is not needed. We will update the readme accordingly. Thanks for the issue!
