### ISSUE TITLE
Use adb to stream to Meta Quest instead of ngrok

### ISSUE THREAD

**Issue by antonioarbues** [OpenTeleVision/TeleVision#12]
Hi,

as it takes just a few minutes of streaming to finish the ngrok free trial, i was looking into other options and i found that on Meta Quest devices it is possible to do some pretty simple port reverse forwarding with the adb (Android) toolkit to be able to access an http server running on the laptop.

here are the details, i think it'd be useful to mention it in the readme

https://medium.com/@lazerwalker/how-to-easily-test-your-webvr-and-webxr-projects-locally-on-your-oculus-quest-eec26a03b7ee

**Comment by chengxuxin** [comment]
Thanks for your information. adb seems to be a good way for Quest local streaming. Will add to readme.

**Comment by i6bimua** [comment]
Thanks for you contribution! But I found that there is a missing description for that.
For users who want to use local streaming,remember change the corresponding code just like described in network streaming
which means you should use
`self.tv = OpenTeleVision(self.resolution_cropped, self.shm.name, image_queue, toggle_streaming, ngrok=True)`
hope that will help you to reconstruct this job,good luck!
