### ISSUE TITLE
'install ca-certificates on VisionPro: mkcert -CAROOT.' What does '-CAROOT' represent and how should it be filled in?

### ISSUE THREAD

**Issue by le-wei** [OpenTeleVision/TeleVision#14]
"Thank you very much for releasing such excellent work. I have some confusion regarding step 6 of the certificate generation: 'install ca-certificates on VisionPro: mkcert -CAROOT.' What does '-CAROOT' represent and how should it be filled in? Also, what does 'core==1.0.1' in the dependency files represent? I hope to get your clarification on these matters. Once again, thank you for your efforts."

**Comment by chengxuxin** [comment]
Just type `mkcert -CAROOT` as is in your terminal and it will return where the certificate is located so you can copy it to your Vision Pro/Mac/Ubuntu...

**Comment by RexSkywalkerLee** [comment]
For the package dependency bug, please update to the latest version. This bug is caused by legacy code and has been fixed in an earlier update.

**Comment by le-wei** [comment]
Thank you very much for your reply. I have already proceeded with the latest code.
