### ISSUE TITLE
Code for Meta Quest 3 support.

### ISSUE THREAD

**Issue by weipeilun** [OpenTeleVision/TeleVision#2]
Hi:

I'm using a Meta Quest 3 device, connected my PC using SteamVR and OpenXR, and can read both left and right eye pose using pyopenxr in realtime.
Can you release your support for Quest 3, and perfect the instructions?
Thank you.

**Comment by weipeilun** [comment]
Connected to my Quest3 followed the introduction. There is no extra code need for Quest3 support. My bad, close the issue.

**Comment by weipeilun** [comment]
Connected to my Quest3 followed the introduction. There is no extra code need for Quest3 support. My bad, close the issue.

**Comment by elevenjiang1** [comment]
Do quest3 in local streaming need any setup?  
Do quest3 aslo need to set the mkcert?
