### ISSUE TITLE
Problems with the use of teleop_hand.py

### ISSUE THREAD

**Issue by tobottyx** [OpenTeleVision/TeleVision#32]
Hello, thank you very much for your work. However, when I use it, I find that there is no collision, and the dexterous hand and the model remain in a penetrating state no matter how they are adjusted. How can I solve this problem?

**Comment by tobottyx** [comment]
I noticed that your code hand is not in the same collision group as the other collisions

**Comment by tobottyx** [comment]
I noticed that your code hand is not in the same collision group as the other collisions

**Comment by kenchen3000** [comment]
@tobottyx  Can i ask whether and how you fixed this? thanks!

**Comment by tobottyx** [comment]
> [@tobottyx](https://github.com/tobottyx) Can i ask whether and how you fixed this? thanks!

Please refer to the official isaacgym documentation to set the collision groups you need
