### ISSUE TITLE
what is the meaning of VR returning to the TeleVision.py?

### ISSUE THREAD

**Issue by jiqimao-1** [OpenTeleVision/TeleVision#39]
Please tell me the following's value's meaning.

`self.left_hand_shared[:] = event.value["leftHand"]
 self.right_hand_shared[:] = event.value["rightHand"]
 self.left_landmarks_shared[:] = np.array(event.value["leftLandmarks"]).flatten()
 self.right_landmarks_shared[:] = np.array(event.value["rightLandmarks"]).flatten()`

I only know that left_hand_shared[:] is a list with 16 datas and  self.left_landmarks_shared[:] is a 25x3 matrix.But the 16 datas's meaning and the 25x3 matrix's every row's 3 data's meaning.
Please tell me ,thank you.

**Comment by geyang** [comment]
there are 25 landmarks on each hand, we return the position for each in
this version of our code.

The 16 are entries in a column-major transformation matrix. You can look it
up here:

https://docs.vuer.ai/en/latest/examples/19_hand_tracking.html#matrix-format

**Comment by jiqimao-1** [comment]
Thank you very much, the help is very important and useful for me.

**Comment by geyang** [comment]
My pleasure!
