### ISSUE TITLE
Inspire hand hardware latency

### ISSUE THREAD

**Issue by qianqianlo** [OpenTeleVision/TeleVision#8]
Dear authors, 

Nice work! We'are also working on inspire hand control and data collection similiar as your teleporation system. Here we've met a problem about hardware latency. We're using inspire hand via 485 serial and ROS, and have noticed that there's a time delay of 0.3s. I'm wondering the way you connect the inspire hand and IPC, and the time delay of your hand control system? 

Also, could you tell me the way you read the data feedback of inspire hand (to collect data)?

Thanks!

**Comment by chengxuxin** [comment]
We did not notice such a large delay. We use Unitree's SDK for inspire robotics. 
[https://support.unitree.com/home/zh/H1_developer/Dexterous_hand](Here)

**Comment by qianqianlo** [comment]
Thanks for your reply and documents!
